dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=flickr setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: kRFxee6hjKfEOIfWtVRgZeZRCxb78SdN0ZJADM0iDkA8kXGPjtlQNoCqb+TCTPfqvyy8OUG+3sZC2YCKDristkSBoE2PC3iMOueTDZxSGoSkV7Nn90Eld5V7QDJKsyyGbY6x0Ka6r4szs1YZDag6Nge4CRf8pYPthr1pBkC0+mI=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
